POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{
   "email": "al2eeex@gmail.com",
   "password": "aee2le@x483je"
}      

#####
POST http://localhost:8080/user/register  HTTP/1.1
Content-Type: application/json

{
    "firstname": "aleeex",
    "middlename":"",
    "lastname":"sheeaw",
    "email": "aleeex2@gmail.com",
    "password": "aeele3@x483je",
    "organisation":"f3ose",
    "position":"",
    "location":"purene",
    "phone":"98323457824"
}

################################
POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{
   "email": "aleeex2@gmail.com",
   "password": "aeele3@x483je"
}      

